### ISSUE TITLE
Remove email address from mistakes_and_corrections.md

### ISSUE THREAD

**Issue by rjsmith** [pri5m/Learning-log#2]
Suggest you remove / obscure your email address on the [mistakes_and_corrections.md](https://github.com/pri5m/Learning-log/blob/master/Intro_into_web_development/HTML/mistakes_and_corrections.md) file, to prevent unwanted attention / webcrawlers picking up your email address (remember public repos on github are open for the entire internet to see!).

**Comment by pri5m** [comment]
Good point!
